/*
 * This source file was generated by the Gradle 'init' task
 */
package webdriver_singleton;

import org.openqa.selenium.WebDriver;

public class App {
    public static void main(String[] args) {
        System.out.println("Getting the first driver instance...");
        WebDriver driver1 = WebDriverManager.getDriver();
        System.out.println("Driver instance 1: " + driver1);
        System.out.println("Getting the second driver instance...");
        WebDriver driver2 = WebDriverManager.getDriver();
        System.out.println("Driver instance 2: " + driver2);

        if(driver1 == driver2) {
            System.out.println("Both driver instances are the same.");
        } else {
            System.out.println("Driver instances are different.");
        }

        driver1.get("https://cred.club/");

        try {
            Thread.sleep(10000);
        } catch (Exception e) {
            e.printStackTrace();
        }

        System.out.println("Quitting the driver...");
        WebDriverManager.quitDriver();
    }
}
