/*
 * This source file was generated by the Gradle 'init' task
 */
package strategy_pattern;

import strategy_pattern.strategy.AdminValidationStrategy;
import strategy_pattern.strategy.NewUserValidationStrategy;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        User admin = new User("ritesh_admin", "admin");
        User newUser = new User("raj", "new");

        ValidationContext context = new ValidationContext(new AdminValidationStrategy());
        System.out.println("Admin valid: " + context.validateUser(admin));

        context.setStrategy(new NewUserValidationStrategy());
        System.out.println("New User valid: " + context.validateUser(newUser));
    }
}
