/*
 * This source file was generated by the Gradle 'init' task
 */
package webdriver_singleton;

import org.junit.jupiter.api.Test;
import org.openqa.selenium.WebDriver;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
   @Test void testSameInstance() {
    WebDriver driver1 = WebDriverManager.getDriver();
    WebDriver driver2 = WebDriverManager.getDriver();
    assertSame(driver1, driver2, "Both driver instances should be the same.");

    WebDriverManager.quitDriver();
   }
}
